server:
  port: 8080

spring:
  application:
    name: popcorn-palace
  datasource:
    url: jdbc:postgresql://localhost:5433/popcorn-palace # 5432 for local
    username: popcorn-palace
    password: popcorn-palace
    driverClassName: org.postgresql.Driver
    platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create #
    properties:
      hibernate:
        format_sql: true # log
    defer-datasource-initialization: true # create tables before inserting the data
  sql:
    init:
      mode: always

  logging:
    level:
      org.springframework.jdbc.datasource.init: trace
      org.springframework.jdbc.datasource.init.ScriptUtils: debug
